baseURL = "https://drakon-prizrak.com/"
languageCode = "en-us"
title = "Drakon Prizrak"
theme = "hugograyscale"

copyright = "Copyright (c) Drakon Prizrak."
canonifyurls = true
paginate = 3

[params]
description = "Drakon Prizrak: A multicultural metal band from Japan."
