[languages]
[languages.en]
languageName = "English"
weight = 2

description = "Drakon Prizrak: A multicultural metal band from Japan."
top = "Home"
menuText = "Menu"

[languages.en.languageSwitcher]
text = "日本語"
flag = "Japan.svg"
target = "/"

[[languages.en.menus]]
  text = "about"
  target= "#about"

[[languages.en.menus]]
  text = "members"
  target= "#members"

[[languages.en.menus]]
  text = "live"
  target= "#live"

[[languages.en.menus]]
  text = "contact"
  target= "#contact"

[languages.en.about]
  header = "About Drakon Prizrak"
  text = 'We are a multicultural gothic metal band with symphonic influences from Tokyo.<br />All of our members have different nationalities.'

[languages.en.members]
header = "Members"
nationality = "Nationality"
instrument = "Instrument"
bands = "Favourite bands"
loves = "Loves"

[[languages.en.members.members]]
  name = "Steri"
  picture = "Steri.jpg"
  nationality = "Greece"
  flag = "Greece.svg"
  instrument = "Vocals / Programming"
  bands = "Evanescence / Nightwish / In This Moment / Korn"
  loves = "Soy Latte / Vegan Moussaka / Cats / The Occult"
  [languages.en.members.members.socialhandles]
    twitter = "https://twitter.com/sterikogias"
    instagram = "https://www.instagram.com/sterikogias/"
    facebook = "https://www.facebook.com/sterikogias"

[[languages.en.members.members]]
  name = "Alya"
  picture = "Alya.jpg"
  nationality = "Russia"
  flag = "Russia.svg"
  instrument = "Bass"
  bands = "Rammstein / Pink Floyd / Scorpions"
  loves = "Playing mobile games"
  [languages.en.members.members.socialhandles]
    twitter = "https://twitter.com/elegantbass"
    instagram = "https://www.instagram.com/aya_drakon"
    facebook = "https://www.facebook.com/profile.php?id=100000228759105"

[[languages.en.members.members]]
  name = "Andreas"
  picture = "Andreas.jpg"
  nationality = "Belgium"
  flag = "Belgium.svg"
  instrument = "Guitar"
  bands = "Iron Maiden / Sodom / After Forever / Samantha Fish"
  loves = "Gaming / Metal / Linux / Pro Wrestling"
  [languages.en.members.members.socialhandles]
    twitter = "https://twitter.com/Metallion98"
    "dorian Guitars" = "https://www.facebook.com/Sophidox/"

[[languages.en.members.members]]
  name = "Jumpei"
  picture = "Jumpei.jpg"
  nationality = "Japan"
  flag = "Japan.svg"
  instrument = "Drums"
  bands = "Miles Davis Quintet / Keith Jarrett Trio / Avishai Cohen Trio"
  loves = "Trying various types of food"
  [languages.en.members.members.socialhandles]
    instagram = "https://www.instagram.com/jp_drakon"

[languages.en.live]
header = "Live events"
past_lives = "Past live events"
entrance = "Entrance"
access = "Access"


[[languages.en.live.events]]
  date = "2019-07-06"
  weekday = "Saturday"
  title = ""
  open = "12:00"
  start = "12:30"
  drakon_start = "19:00"
  entrance = "1500 yen"
  venue_name = "Shimo-Kitazawa Waver"
  venue_address = "〒155-0031 Tokyo-to Setagaya-ku Kitazawa 2-14-13 B1F"
  venue_access = "http://waverwaver.net/pc/access/"
  google_map = '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1362.9408142184493!2d139.66624681586987!3d35.66129378509946!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6018ee0fc1cbb5ef%3A0xb97bfa62349bbb69!2sWAVER!5e0!3m2!1sen!2sjp!4v1557485744207!5m2!1sen!2sjp" allowfullscreen></iframe>'

[[languages.en.live.events]]
  date = "2019-04-18"
  weekday = "Thursday"
  title = "Tsuji-san 40th guitar anniversary live event"
  start = "18:00"
  drakon_start = "20:00"
  entrance = "1000 yen"
  venue_name = "Shinjuku Gyoen Sound"
  venue_address = "〒160-0022 Tokyo-to Shinjuku-ku Shinjuku 2-3-12 B1F"
  venue_access = "http://gyoen-sound.com/access.html"
  google_map = "!1m14!1m8!1m3!1d4582.831632100654!2d139.7074435205412!3d35.68804824942547!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188cc33dd89ead%3A0x3bdd383c615345d8!2z44CSMTYwLTAwMjIg5p2x5Lqs6YO95paw5a6_5Yy65paw5a6_77yS5LiB55uu77yT4oiS77yR77yS!5e0!3m2!1sja!2sjp!4v1557410464030!5m2!1sja!2sjp"

[languages.en.contact]
  header = "Contact us"
  text = "We are always looking for more gigs. Contact us through our social media or e-mail."
