baseURL = "https://drakon-prizrak.com/"
languageCode = "en-us"
title = "Drakon Prizrak"
theme = "hugograyscale"
copyright = "Drakon Prizrak"
DefaultContentLanguage = "jp"

canonifyurls = true
paginate = 3
[params]
visiblePastLives = 1

[params.socialhandles]
    instagram = "https://instagram.com/drakonprizrakofficial"
    youtube =   "https://youtube.com/channel/UCY1jxlZ3nHRgT51OOfSKhVA"
    twitter =   "https://twitter.com/DrakonPrizrak"
    facebook =  "https://www.facebook.com/drakonprizrakofficial"
