[languages]
[languages.en]
languageName = "English"
weight = 2

description = "Drakon Prizrak: A multicultural metal band from Japan."
top = "Home"
menuText = "Menu"

[languages.en.languageSwitcher]
text = "日本語"
flag = "Japan.svg"
target = "/"

[[languages.en.menus]]
  text = "about"
  target= "#about"

[[languages.en.menus]]
  text = "members"
  target= "#members"

[[languages.en.menus]]
  text = "live"
  target= "#live"

[[languages.en.menus]]
  text = "Discography"
  target= "#discography"

[[languages.en.menus]]
  text = "Merch"
  target= "#merch"

[[languages.en.menus]]
  text = "contact"
  target= "#contact"

[languages.en.about]
  header = "Drakon Prizrak"
  text = 'A multicultural metal band from Tokyo.<br />All of our members have different nationalities.'

[languages.en.members]
header = "Members"
nationality = "Nationality"
instrument = "Instrument"
bands = "Favourite bands"
loves = "Loves"

[[languages.en.members.members]]
  id = "soikkam"
  name = "Soikkam"
  picture = "Soikkam.jpg"
  nationality = "USA"
  flag = "USA.svg"
  instrument = "Vocals"
  bands = "Malice Mizer / Versailles / Crimson Glory / Winterhawk"
  loves = "Karaoke / Magic the Gathering / Basketball / Animals"
  [languages.en.members.members.socialhandles]
    twitter = "https://twitter.com/SoikkamVoxx"
    instagram = "https://www.instagram.com/singerofthe7seas/"
    facebook = "https://www.facebook.com/SoikkamOfficial"

[[languages.en.members.members]]
  id = "alya"
  name = "Alya"
  picture = "Alya.jpg"
  nationality = "Russia"
  flag = "Russia.svg"
  instrument = "Bass"
  bands = "Rammstein / Pink Floyd / Scorpions"
  loves = "Playing mobile games"
  [languages.en.members.members.socialhandles]
    twitter = "https://twitter.com/elegantbass"
    instagram = "https://www.instagram.com/aya_drakon"
    facebook = "https://www.facebook.com/profile.php?id=100000228759105"

[[languages.en.members.members]]
  id = "andreas"
  name = "Andreas"
  picture = "Andreas.jpg"
  nationality = "Belgium"
  flag = "Belgium.svg"
  instrument = "Guitar"
  bands = "Iron Maiden / Sodom / After Forever /<br />Samantha Fish"
  loves = "Gaming / Metal / Linux / Pro Wrestling"
  [languages.en.members.members.socialhandles]
    twitter = "https://twitter.com/Metallion98"
    "dorian Guitars" = "https://www.facebook.com/Sophidox/"

[[languages.en.members.members]]
  id = "jumpei"
  name = "Jumpei"
  picture = "Jumpei.jpg"
  nationality = "Japan"
  flag = "Japan.svg"
  instrument = "Drums"
  bands = "Miles Davis Quintet / Keith Jarrett Trio /<br />Avishai Cohen Trio"
  loves = "Trying various types of food"
  [languages.en.members.members.socialhandles]
    instagram = "https://www.instagram.com/jp_drakon"

[[languages.en.members.members]]
  id = "moncader"
  name = "Moncader"
  picture = "Moncader.jpg"
  nationality = "Canada"
  flag = "Canada.svg"
  instrument = "DSLR Camera"
  bands = "S3RL / Linkin Park / Lindsey Stirling"
  loves = "Gaming / Wikipedia / Walking / Outdoors"
  [languages.en.members.members.socialhandles]
    instagram = "https://www.instagram.com/moncader"
    twitter = "https://twitter.com/moncader"

[languages.en.live]
header = "Live events"
past_lives = "Past live events"
entrance = "Entrance"
access = "Access"
yen = " yen"
pending = "TBA"
cancelled = "cancelled"
corona = "<p>Due to the covid-19 virus, all live events have been postponed until further notice.</p><p>Instead we are focusing on recording our first EP titled &quot;Hell&apos;s Gates&quot;.<br>Please <a class='js-scroll-trigger' href='#contact'>follow us on social media</a> for any news regarding the EP or future live events.</p>"

[languages.en.discography]
header = "Discography"
text = "<p>We are in the final stages of recording our first EP titled:<br><strong>Hell&apos;s Gates</strong></p><p>Please <a class='js-scroll-trigger' href='#contact'>follow us on social media</a> for any news.</p>"

[languages.en.merch]
header = "Merchandise"
text = "Official Drakon Prizrak T-shirt."
price = "¥2000"
subtext = "On sale at all live events or by contacting us."

[languages.en.contact]
  header = "Contact us"
  text = "We are always looking for more gigs.<br />Contact us through our social media or e-mail."
