[languages]
[languages.jp]
languageName = "日本語"
weight = 2

description = "多国籍メタルバンドDrakon Prizrak。"
top = "Top"
menuText = "メニュー"

[languages.jp.languageSwitcher]
Text = "English"
Flag = "UK.svg"
target = "/en"

[[languages.jp.menus]]
  text = "Drakon Prizrak"
  target= "#about"

[[languages.jp.menus]]
  text = "メンバー"
  target= "#members"

[[languages.jp.menus]]
  text = "ライブ"
  target= "#live"

[[languages.jp.menus]]
  text = "CD"
  target= "#discography"

[[languages.jp.menus]]
  text = "グッズ"
  target= "#merch"

[[languages.jp.menus]]
  text = "お問い合わせ"
  target= "#contact"

[languages.jp.about]
    header = "Drakon Prizrak"
    katakana = "ドラコン・プリズラック"
    text = '多国籍メタルバンド。<br />ロシア、ベルギー、アメリカ、九州から、<br />東京に集結！'

[languages.jp.members]
header = "メンバー"
nationality = "国籍"
instrument = "パート"
bands = "影響を受けたバンド"
loves = "趣味"

[[languages.jp.members.members]]
  id = "soikkam"
  name = "スァッカム"
  picture = "Soikkam.jpg"
  nationality = "アメリカ"
  flag = "USA.svg"
  instrument = "ボーカル"
  bands = "MALICE MIZER / Versailles /<br />クリムゾン・グローリー  / ウィンターホーク"
  loves = "カラオケ / マジック：ザ・ギャザリング / バスケ"
  [languages.jp.members.members.socialhandles]
    twitter = "https://twitter.com/SoikkamVoxx"
    instagram = "https://www.instagram.com/singerofthe7seas/"
    facebook = "https://www.facebook.com/SoikkamOfficial"

[[languages.jp.members.members]]
  id = "alya"
  name = "アリャ"
  picture = "Alya.jpg"
  nationality = "ロシア"
  flag = "Russia.svg"
  instrument = "ベース"
  bands = "ラムシュタイン / ピンク・フロイド / スコーピオンズ"
  loves = "モバイルゲーム"
  [languages.jp.members.members.socialhandles]
    twitter = "https://twitter.com/elegantbass"
    instagram = "https://www.instagram.com/aya_drakon"
    facebook = "https://www.facebook.com/profile.php?id=100000228759105"

[[languages.jp.members.members]]
  id = "andreas"
  name = "アンドレアス"
  picture = "Andreas.jpg"
  nationality = "ベルギー"
  flag = "Belgium.svg"
  instrument = "ギター"
  bands = "アイアン・メイデン / ソドム /<br />アフター・フォーエヴァー / サマンサ・フィッシュ"
  loves = "ゲーム / メタル / リナックス / プロレス"
  [languages.jp.members.members.socialhandles]
    twitter = "https://twitter.com/Metallion98"
    "dorian Guitars" = "https://www.facebook.com/Sophidox/"

[[languages.jp.members.members]]
  id = "jumpei"
  name = "ジュンペイ"
  picture = "Jumpei.jpg"
  nationality = "日本（九州）"
  flag = "Japan.svg"
  instrument = "ドラム"
  bands = "マイルス・デイヴィス・クインテット / キース・ジャレット・トリオ / アヴィシャイ ・コーエン・トリオ"
  loves = "食べ歩き"
  [languages.jp.members.members.socialhandles]
    instagram = "https://www.instagram.com/jp_drakon"

[[languages.jp.members.members]]
  id = "moncader"
  name = "モンカダー"
  picture = "Moncader.jpg"
  nationality = "カナダ"
  flag = "Canada.svg"
  instrument = "撮影カメラ"
  bands = "S3RL / リンキン・パーク / リンジー・スターリング"
  loves = "ゲーム / ウィキペディア / 散歩 / アウトドア"
  [languages.jp.members.members.socialhandles]
    instagram = "https://www.instagram.com/moncader"
    twitter = "https://twitter.com/moncader"

[languages.jp.live]
header = "ライブ"
past_lives = "過去のライブ"
entrance = "入場"
access = "アクセス"
yen = "円"
pending = "未定"
cancelled = "延期"
no_gigs_planned = "現在ライブイベントの予定はありません。<br>近日再開予定です。"
tickets = "チケット"
livestream = "ライブ配信"

[languages.jp.discography]
header = "CD"
text = "<p>ご要望の多かった初EP<br><strong>『Hell&apos;s Gates』</strong><br><a href=\"https://drakonprizrak.bandcamp.com\" target=\"_blank\">https://drakonprizrak.bandcamp.com</a><br>ダウンロード版 800円<br>CD版 1200円 &#40;ライブ会場購入1000円&#41;</p>"

[languages.jp.merch]
header = "グッズ"
text = "Drakon Prizrak オリジナルTシャツ。"
price = "2000円"
subtext = "ライブ会場物販にて販売中。<br />メールやSNSにて直接ご注文も承ります。"

[languages.jp.contact]
  header = "お問い合わせ"
  text = "ライブのご依頼はSNS、メール等で<br />いつでも受け付けております"
