date = ""

title_en = ""
title_jp = ""

open = ""
start = ""
drakon_start = ""
entrance = ""

venue_name_en = ""
venue_name_jp = ""

venue_address_en = ""
venue_address_jp = ""

venue_access = ""
google_map = ''
